### ISSUE TITLE
[TODO] 멀티플레이시 아이템 파밍 박스 동작

### ISSUE THREAD

**Issue by HUSK-321** [HUSK-321/FantasyApocalypse#46]
- [x] F UI 는 근처에 있는 플레이어에게만 나오게 설정
- [x] 디졸브 효과는 모두가 볼 수 있게 설정
- [x] 디졸브가 되면 더이상 파밍이 되지 않도록 수정
- [x] 아이템이 나올 시 drop 효과가 모두에게 보이게 설정
