### ISSUE TITLE
[TODO] 면접 전까지 수정해야 할 부분 목록

### ISSUE THREAD

**Issue by HUSK-321** [HUSK-321/FantasyApocalypse#81]
- [ ] 인게임 ESC 메뉴 추가
- [x] 타 스크립트들의 컨트롤러 참조 줄이기
- [ ] 그 외 기타 스크립트의 TODO 주석 처리
